// Code generated by ledger-builder. DO NOT EDIT.

package core

// Metadata is a representation of the metadata of any given resource managed by
// the API server. Clients should not set the fields of Metadata directly.
type Metadata struct {
	ID      string // ID is the unique identifier of the resource.
	Version uint64 // Version is the version of the resource as it is known to the Ledger.

	// IsDeleted indicates whether the resource has been marked as deleted.
	// If true, the resource has been soft-deleted but may still exist in the system.
	// No further operations can be performed on the resource.
	IsDeleted bool
}
