// Code generated by ledger-builder. DO NOT EDIT.

package core

// Metadata is a representation of the metadata of any given resource managed by
// the API server. Clients should not set the fields of Metadata directly.
type Metadata struct {
	ID      string // ID is the unique identifier of the resource.
	Version uint64 // Version is the version of the resource as it is known to the Ledger.
}
